version: '3.5'
services:
  rabbitmq:
    image: rabbitmq:3.12.7-management
    container_name: js-and-ts-apps-teamwise-nx-ws.rabbitmq
    ports:
      - '1084:15672'
      - '5672:5672'
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: test
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:16-alpine
    container_name: js-and-ts-apps-teamwise-nx-ws.users.postgres
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "js-and-ts-apps-teamwise-nx-ws.users"
    ports:
      - "1000:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d js-and-ts-apps-teamwise-nx-ws" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - postgres

  pgadmin:
    container_name: js-and-ts-apps-teamwise-nx-ws.users.pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.local"
      PGADMIN_DEFAULT_PASSWORD: "test"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./db:/var/lib/pgadmin
    ports:
      - "2000:80"
    restart: unless-stopped
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
