#HISTORY

# @name CREATE USER
POST {{baseUrl}}{{route}} HTTP/1.1
Content-Type: application/json

{
  "name": "kate",
  "email": "78wqq13o@ya.ru",
  "dateBirth": "2022-02-01",
  "isAdmin": true
}
> {%
  client.global.set("userId", response.body.id);
%}
###

# @name GET USERS LIST
GET {{baseUrl}}/{{route}}?sort=asc&limit=2&page=1 HTTP/1.1
Accept: application/json

> {%
  //update userId with random id string from response array
  client.global.set("userId", response.body[Math.round(response.body.length*Math.random())].id);
%}
###
